---
title: "diagrams"
author: "MH Tessler"
date: "10/29/2020"
output: pdf_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(ggVennDiagram)
library(jsonlite)
library(ggplot2)
library(gridExtra)
library(cowplot)
set.seed(20201027)
```


Helper functions

```{r}
genes <- paste("sample",1:100000,sep="")

get_samples_from_df = function(df, field){
  data.frame(df[[field]]) %>%
    pivot_longer(-probs, names_to = "key", values_to = "val") %>%
    group_by(key) %>%
    summarize(prob = sum(val * probs),
              src = field) %>%
    rwebppl::get_samples(., num_samples = 1000)
}

genes <- paste("sample",1:100000,sep="")


get_venn_samples <- function(df_samples){
  
  make_venn_sample <- function(region, i){
    # print(i)
    samp = genes[i]
    A = ifelse(str_detect(region, "A"), samp, NA)
    B = ifelse(str_detect(region, "B"), samp, NA)
    C = ifelse(str_detect(region, "C"), samp, NA)
     return(data.frame(A = A, B = B, C = C))
  }
  x <- imap(df_samples, make_venn_sample) %>%
    bind_rows(.)

  list(
    A = x$A[!is.na(x$A)],
    B = x$B[!is.na(x$B)],
    C = x$C[!is.na(x$C)]
  )
}

venn_diagram_from_df <- function(df){
  df %>%
    gather(key, prob) %>%
    rwebppl::get_samples(., num_samples = 100) %>%
    pull(key) %>% 
    get_venn_samples() %>%
    ggVennDiagram(., label = NULL, color = 'black')+
    scale_fill_gradient(low = "white", high = "grey35",
                        limits = c(0, 100),
                        breaks = c(0, 50, 100),
                        labels = c(0, 0.5, 1),
                        name = "Probability")
}
```

Data frames for Venn Diagrams

```{r}

empty.venn <- data.frame(
  A = 0, B = 0, C = 0, 
  AB = 0, BC = 0, AC = 0,
  ABC = 0
)

barbara.venn <- data.frame(
  A = 0, B = 0, C = 1, 
  AB = 1, BC = 1, AC = 0,
  ABC = 1
)

allsome.venn <- data.frame(
  A = 0, B = 1, C = 1, 
  AB = 1, BC = 1, AC = 0,
  ABC = 0.5
)
```


# Visualizations

```{r}
plot1 <- venn_diagram_from_df(empty.venn) + guides(fill = F)
plot2 <- venn_diagram_from_df(barbara.venn) + guides(fill = F)
plot3 <- venn_diagram_from_df(allsome.venn) + guides(fill = F)

plot_grid(plot1, plot2, plot3, ncol=3,
          labels = c("i", "ii", "iii"))
```


All As are Bs
All Bs are Cs

```{r}
# 'ABC', 'ABC;BC', 'ABC;C', 'ABC;BC;C'

all.all.1 <- data.frame(
  A = 0, B = 0, C = 0, 
  AB = 0, BC = 0, AC = 0,
  ABC = 1
)

all.all.2 <- data.frame(
  A = 0, B = 0, C = 0, 
  AB = 0, BC = 1, AC = 0,
  ABC = 1
)

all.all.3 <- data.frame(
  A = 0, B = 0, C = 1, 
  AB = 0, BC = 0, AC = 0,
  ABC = 1
)

all.all.4 <- data.frame(
  A = 0, B = 0, C = 1, 
  AB = 0, BC = 1, AC = 0,
  ABC = 1
)



aa1 <- venn_diagram_from_df(all.all.1) + guides(fill = F)
aa2 <- venn_diagram_from_df(all.all.2) + guides(fill = F)
aa3 <- venn_diagram_from_df(all.all.3) + guides(fill = F)
aa4 <- venn_diagram_from_df(all.all.4) + guides(fill = F)


plot_grid(aa1, aa2, aa3, aa4, ncol=4)#,
          #labels = c("i", "ii", "iii", "iv"))

ggsave("diagrams_allAB_allBC.pdf", width = 9, height = 2.25)

```


No As are Bs
Some Bs are Cs

[
  'BC',       'AC;BC',
  'A;BC',     'A;AC;BC',
  'B;BC',     'B;AC;BC',
  'A;B;BC',   'A;B;AC;BC',
  
  'BC;C',     'AC;BC;C',
  'A;BC;C',   'A;AC;BC;C',
  'B;BC;C',   'B;AC;BC;C',
  'A;B;BC;C', 'A;B;AC;BC;C'
]

```{r}

none.some.1 <- data.frame(
  A = 0, B = 0, C = 0, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.2 <- data.frame(
  A = 0, B = 0, C = 0, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.3 <- data.frame(
  A = 1, B = 0, C = 0, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.4 <- data.frame(
  A = 1, B = 0, C = 0, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.5 <- data.frame(
  A = 0, B = 1, C = 0, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.6 <- data.frame(
  A = 0, B = 1, C = 0, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.7 <- data.frame(
  A = 1, B = 1, C = 0, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.8 <- data.frame(
  A = 1, B = 1, C = 0, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.9 <- data.frame(
  A = 0, B = 0, C = 1, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.10 <- data.frame(
  A = 0, B = 0, C = 1, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.11 <- data.frame(
  A = 1, B = 0, C = 1, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.12 <- data.frame(
  A = 1, B = 0, C = 1, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.13 <- data.frame(
  A = 0, B = 1, C = 1, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.14 <- data.frame(
  A = 0, B = 1, C = 1, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

none.some.15 <- data.frame(
  A = 1, B = 1, C = 1, 
  AB = 0, BC = 1, AC = 0,
  ABC = 0
)

none.some.16 <- data.frame(
  A = 1, B = 1, C = 1, 
  AB = 0, BC = 1, AC = 1,
  ABC = 0
)

ns1 <- venn_diagram_from_df(none.some.1) + guides(fill = F)
ns2 <- venn_diagram_from_df(none.some.2) + guides(fill = F)
ns3 <- venn_diagram_from_df(none.some.3) + guides(fill = F)
ns4 <- venn_diagram_from_df(none.some.4) + guides(fill = F)
ns5 <- venn_diagram_from_df(none.some.5) + guides(fill = F)
ns6 <- venn_diagram_from_df(none.some.6) + guides(fill = F)
ns7 <- venn_diagram_from_df(none.some.7) + guides(fill = F)
ns8 <- venn_diagram_from_df(none.some.8) + guides(fill = F)
ns9 <- venn_diagram_from_df(none.some.9) + guides(fill = F)
ns10 <- venn_diagram_from_df(none.some.10) + guides(fill = F)
ns11 <- venn_diagram_from_df(none.some.11) + guides(fill = F)
ns12 <- venn_diagram_from_df(none.some.12) + guides(fill = F)
ns13 <- venn_diagram_from_df(none.some.13) + guides(fill = F)
ns14 <- venn_diagram_from_df(none.some.14) + guides(fill = F)
ns15 <- venn_diagram_from_df(none.some.15) + guides(fill = F)
ns16 <- venn_diagram_from_df(none.some.16) + guides(fill = F)




plot_grid(ns1, ns2, ns3, ns4,
          ns5, ns6, ns7, ns8,
          ns9, ns10, ns11, ns12,
          ns13, ns14, ns15, ns16, ncol=4)

ggsave("diagrams_noneAB_someBC.pdf", width = 9, height = 7)

```

