---
title: "model_simulations"
author: "MH Tessler"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
library(rwebppl)
library(tidyverse)
library(ggVennDiagram)
library(jsonlite)
library(ggplot2)
library(gridExtra)
library(ggthemes)
theme_set(theme_few())
set.seed(20201027)
```


Helper functions

```{r}
# get_samples_from_df = function(df){
#   data.frame(df) %>%
#     pivot_longer(-prob, names_to = "key", values_to = "val") %>%
#     group_by(key) %>%
#     summarize(prob = sum(val * prob)
#               ) %>%
#     rwebppl::get_samples(., num_samples = 1000)
# }
# 
# get_samples_from_df = function(df, field1){
#   data.frame(df[[field1]]) %>%
#     pivot_longer(-probs, names_to = "key", values_to = "val") %>%
#     group_by(key) %>%
#     summarize(prob = sum(val * probs),
#               src = field1
#               ) %>%
#     rwebppl::get_samples(., num_samples = 1000)
# }

get_samples_from_df = function(df, field1, field2){
  data.frame(df[[field1]][[field2]]) %>%
    pivot_longer(-probs, names_to = "key", values_to = "val") %>%
    group_by(key) %>%
    summarize(prob = sum(val * probs),
              utterance = field1,
              src = field2
              ) %>%
    rwebppl::get_samples(., num_samples = 1000)
}

genes <- paste("sample",1:100000,sep="")

get_venn_samples <- function(df_samples){
  
  make_venn_sample <- function(region, i){
    # print(i)
    samp = genes[i]
    A = ifelse(str_detect(region, "A"), samp, NA)
    B = ifelse(str_detect(region, "B"), samp, NA)
    C = ifelse(str_detect(region, "C"), samp, NA)
     return(data.frame(A = A, B = B, C = C))
  }
  x <- imap(df_samples, make_venn_sample) %>%
    bind_rows(.)

  list(
    A = x$A[!is.na(x$A)],
    B = x$B[!is.na(x$B)],
    C = x$C[!is.na(x$C)]
  )
}


get_qud_samples <- function(df_samples){
  
  make_qud_sample <- function(region, i){
    # print(i)
    samp = genes[i]
    A = ifelse(str_detect(region, "A"), samp, NA)
    C = ifelse(str_detect(region, "C"), samp, NA)
     return(data.frame(A = A, C = C))
  }
  x <- imap(df_samples, make_qud_sample) %>%
    bind_rows(.)

  list(
    A = x$A[!is.na(x$A)],
    C = x$C[!is.na(x$C)]
  )
}



format_sentence = function(sentence){
  split_sentences = str_split(sentence, "/")[[1]]
  n_sentences = length(split_sentences)
  formatted_sentences = c()
  for (sent in split_sentences){
    sentence_parts = str_split(sent, ";")[[1]]
    q1 = ifelse(sentence_parts[1] == "None", "No",
          ifelse(sentence_parts[1] == "Some not", "Some",
                      sentence_parts[1]))
    q2 = ifelse(sentence_parts[1] == "Some not", "not ", "")
    formatted_sentence = paste(
        q1, " ",
        paste(sentence_parts[2], "s", sep = ""),
        " are ",
        q2,
        paste(sentence_parts[3], "s", sep = ""),
        sep = ""
      )
    formatted_sentences <- c(formatted_sentences, formatted_sentence)
  }
  paste(formatted_sentences, collapse = "\n")
}

extract_term_order = function(sentence){
  sentence_parts = str_split(sentence, ";")[[1]]
  if (sentence_parts[1] == "NVC"){
    return("NVC")
  }
  return(
    paste(
      paste(sentence_parts[2], "s", sep = ""),
      " are ",
      paste(sentence_parts[3], "s", sep = ""),
      sep = ""
    )
  )
}

make_venn_digram <- function(df, utt, qud){
  venn_sample_fn = ifelse(qud == "qud", get_qud_samples, get_venn_samples)
  ggVennDiagram(venn_sample_fn(
    df %>% filter(utterance == utt) %>% pull(key)
  ), label = NULL, color = 'black') +
    ggtitle(format_sentence(utt)) + 
    scale_fill_gradient(low = "white", high = "grey10",
                        limits = c(0, 1000),
                        breaks = c(0, 500, 1000),
                        labels = c(0, 0.5, 1),
                        name = "Probability")+
    # guides(fill = F)+
    theme(plot.title = element_text(hjust = 0.5))
}
```

Run Webppl Model

```{r}


# syllogism <- data.frame(
#   p1 = c("A", "B"),
#   p2 = c("B", "C"),
#   quantifier = c("some", "some")
# ) 

wp.rs <- webppl(
  program_file = "venn-r-refac.wppl",
  data = "M00_LIT_LIT",
  data_var = "dataFromR",
  packages = c("./node_modules/vennUtils_oneShot")
)

# get_venn_samples(get_samples_from_df(wp.rs) %>% pull(key)) %>% ggVennDiagram(.)

# get_samples_from_df

wp.rs.samples <- bind_rows(
  map(names(wp.rs), function(s){
    map(names(wp.rs[[s]]), function(k){
      return(get_samples_from_df(wp.rs, s, k))
    })
  })
)

# wp.rs.samples <- bind_rows(
#   get_samples_from_df(wp.rs, "All;A;B", "literal"),
#   get_samples_from_df(wp.rs, "All;A;B", "pragmatic"),
#   # get_samples_from_df(wp.rs, "All;B;A"),
#   get_samples_from_df(wp.rs, "Some;A;B", "literal"),
#   get_samples_from_df(wp.rs, "Some;A;B", "pragmatic"),
#   # get_samples_from_df(wp.rs, "Some;B;A"),
#   get_samples_from_df(wp.rs, "Some not;A;B", "literal"),
#   get_samples_from_df(wp.rs, "Some not;A;B", "pragmatic"),
#   # get_samples_from_df(wp.rs, "Some not;B;A"),
#   get_samples_from_df(wp.rs, "None;A;B", "literal"),#,
#   get_samples_from_df(wp.rs, "None;A;B", "pragmatic")#,
#   # get_samples_from_df(wp.rs, "None;B;A")
# )
```

Literal interpretations

```{r}
all_plots <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x, "state"
                   ) } )

all_plots_qud <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x, "qud"
                   ) } )


legend <- cowplot::get_legend(
  # create some space to the left of the legend
  all_plots[[1]] + theme(legend.box.margin = margin(0, 0, 0, 12))
)

# all_plots[[1]] + ggtitle("")
# ggsave("../publications/topics/figs/venn_AA1_exp.pdf", width = 3, height = 2.5)

# all_plots[[3]] + ggtitle("")
# ggsave("../publications/topics/figs/venn_EI1_exp.pdf", width = 3, height = 2.5)
# plot_grid(prow, legend, rel_widths = c(3, .4))
cowplot::plot_grid(
  cowplot::plot_grid(
    all_plots[[1]] + theme(legend.position="none"),
    all_plots[[2]] + theme(legend.position="none"),
    all_plots[[3]] + theme(legend.position="none"), nrow = 1),
  legend,
  rel_widths = c(3, .4),
  # cowplot::plot_grid(plotlist = all_plots_prag_head, nrow = 1)+ 
  #   theme(plot.margin = unit(c(1,0,0,0), "lines")),
  nrow = 1, #labels = c("literal", "pragmatic state", "pragmatic qud"),# "pragmatic head"),
  label_size = 12,
  labels = c("(i) Full State"),
  label_x = 0, #label_y = 0,
  hjust = -0.15#, #vjust = -0.2
)
ggsave("../publications/topics/figs/venn_literal_AA1_AI1_EI1_exp.pdf", width = 9, height = 4)

```

```{r}
all_plots_qud <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x, "qud"
                   ) } )


cowplot::plot_grid(
  cowplot::plot_grid(
    all_plots_qud[[1]] + theme(legend.position="none"),
    all_plots_qud[[2]] + theme(legend.position="none"),
    all_plots_qud[[3]] + theme(legend.position="none"), nrow = 1),
  legend,
  rel_widths = c(3, .4),
  # cowplot::plot_grid(plotlist = all_plots_prag_head, nrow = 1)+ 
  #   theme(plot.margin = unit(c(1,0,0,0), "lines")),
  nrow = 1, #labels = c("literal", "pragmatic state", "pragmatic qud"),# "pragmatic head"),
  label_size = 12,
  labels = c("(ii) A-C QUD"),
  label_x = 0, #label_y = 0,
  hjust = -0.15#, #vjust = -0.2
)

ggsave("../publications/topics/figs/venn_literal_AA1_AI1_EI1_exp_qud.pdf", width = 8, height = 3)

```


```{r eval = F}
all_plots <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x, "state"
                   ) } )

all_plots_qud <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x, "qud"
                   ) } )


cowplot::plot_grid(
  cowplot::plot_grid(
    cowplot::plot_grid(
      all_plots[[1]] + theme(legend.position="none"),
      all_plots[[2]] + theme(legend.position="none"),
      all_plots[[3]] + theme(legend.position="none"), nrow = 1),
    legend,
    rel_widths = c(3, .4),
    # cowplot::plot_grid(plotlist = all_plots_prag_head, nrow = 1)+ 
    #   theme(plot.margin = unit(c(1,0,0,0), "lines")),
    nrow = 1, #labels = c("literal", "pragmatic state", "pragmatic qud"),# "pragmatic head"),
    label_size = 12,
    label_x = 0, #label_y = 0,
    hjust = -0.15#, #vjust = -0.2
  ),
  cowplot::plot_grid(
    cowplot::plot_grid(
      all_plots_qud[[1]] + theme(legend.position="none") + ggtitle(""),
      all_plots_qud[[2]] + theme(legend.position="none") + ggtitle(""),
      all_plots_qud[[3]] + theme(legend.position="none") + ggtitle(""), nrow = 1),
    legend,
    rel_widths = c(3, .4),
    # cowplot::plot_grid(plotlist = all_plots_prag_head, nrow = 1)+ 
    #   theme(plot.margin = unit(c(1,0,0,0), "lines")),
    nrow = 1, #labels = c("literal", "pragmatic state", "pragmatic qud"),# "pragmatic head"),
    label_size = 12,
    label_x = 0, #label_y = 0,
    hjust = -0.15#, #vjust = -0.2
  ),
  label_size = 12,
  label_x = 0, #label_y = 0,
  hjust = 0, #vjust = -0.2
  nrow = 2, labels = c("(i): Full State", "(ii) A-C QUD")
)

ggsave("../publications/topics/figs/venn_literal_AA1_AI1_EI1_exp_wQUD.pdf", width = 11, height = 4)

```



```{r}


all_plots_lit <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "literal"), x,  "qud"
                   ) + theme(legend.position="none") } )


all_plots_prag_state <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "pragmatic_state"), x, "qud"
                   ) + theme(legend.position="none") } )

all_plots_prag_AC <- map(unique(wp.rs.samples$utterance), 
                 function(x){ make_venn_digram (
                   wp.rs.samples %>% filter(src == "pragmatic_AC"), x,  "qud"
                   ) + theme(legend.position="none") } )

# all_plots_prag_head <- map(unique(wp.rs.samples$utterance), 
#                  function(x){ make_venn_digram (
#                    wp.rs.samples %>% filter(src == "pragmatic_head"), x 
#                    ) } )

cowplot::plot_grid(
  cowplot::plot_grid(plotlist = all_plots_lit, nrow = 1) + 
    #theme(plot.margin = unit(c(1.25,0,1,0), "lines")),
    theme(plot.margin = unit(c(1,0,0,0), "lines")),
  cowplot::plot_grid(plotlist = all_plots_prag_state, nrow = 1)+ 
    theme(plot.margin = unit(c(1,0,0,0), "lines")),
  cowplot::plot_grid(plotlist = all_plots_prag_AC, nrow = 1)+ 
    theme(plot.margin = unit(c(1,0,0,0), "lines")),
  # cowplot::plot_grid(plotlist = all_plots_prag_head, nrow = 1)+ 
  #   theme(plot.margin = unit(c(1,0,0,0), "lines")),
  nrow = 3, 
  labels = c("literal", "pragmatic state", "pragmatic qud"),# "pragmatic head"),
  label_size = 12,
  label_x = 0, #label_y = 0,
  hjust = -0.15#, #vjust = -0.2
)

ggsave("../publications/topics/figs/venn_syllogismsQud_lit_prag.pdf", width = 8, height = 4.5)

```


```{r}
wp.rs.samples %>%
  filter(src %in% c("pragmatic_state", "pragmatic_head")) %>%
  group_by(src, utterance, key) %>%
  count() %>%
  pivot_wider(names_from = key, values_from = n) %>% View()

```


```{r}
# wp.rs.samples <- bind_rows(
#   get_samples_from_df(wp.rs, "sequential"),
#   get_samples_from_df(wp.rs, "pragmatic"),
#   get_samples_from_df(wp.rs, "literal")
# )

# Make Venn Diagram

plot1 <- make_venn_digram(wp.rs.samples, "literal")
plot2 <- make_venn_digram(wp.rs.samples, "pragmatic")
plot3 <- make_venn_digram(wp.rs.samples, "sequential")

grid.arrange(plot1, plot2, plot3, ncol=3)


```


```{r}
data.frame(wp.rs$sequential) %>%
  rowwise() %>%
  mutate(AC = support.AC || support.ABC) %>%
  ungroup() %>%
  group_by(AC) %>%
  count(sum(probs))
  # summarize(sum(!AB))

data.frame(wp.rs$sequential) %>%
  group_by(support.AB, support.ABC) %>%
  count(sum(probs))
```


# Speaker model


```{r}
marginalize_speaker_dist = function(joint_dist, venn, qud){
  return (bind_rows(
  data.frame(wp.rs[[venn]][[qud]]) %>%
    group_by(support.1) %>%
    summarize(marginalProb = sum(probs),
              premise_num = '1') %>%
    ungroup() %>%
    rename(premise = support.1),
  data.frame(wp.rs[[venn]][[qud]]) %>%
    group_by(support.2) %>%
    summarize(marginalProb = sum(probs),
              premise_num = '2') %>%
    ungroup() %>%
    rename(premise = support.2)
  ) %>%
  mutate(
    venn = venn,
    qud = qud
  ))
}
```

```{r}
wp.rs <- webppl(
  program_file = "venn-r.wppl"#,
  # data = syllogism,
  # data_var = "syllogism"
)



venns = names(wp.rs)
quds = names(wp.rs[[venns[1]]])

wp.rs.s.marginals <- bind_rows(
  map(venns, function(venn){
    map(quds, function(qud){
      return(marginalize_speaker_dist(wp.rs, venn, qud))
    })
  })
)
```


Speaker marginals on premises

```{r}
wp.rs.s.marginals %>%
  rowwise() %>%
  mutate(quantifier = str_split(premise, ";")[[1]][1],
         premise_num = factor(premise_num, levels = c("1", "2"),
                              labels = c("As are Bs", "Bs are Cs")),
         qud = factor(qud, levels = c("stateQud", "acQud"),
                      labels = c("State\nQUD", "Conclusion\nQUD")),
         quantifier = factor(quantifier, levels = c("All", "Some",
                                                    "Some not", "No"))) %>%
  ggplot(., aes( fill = quantifier, y = marginalProb,
                               x = premise_num, group = quantifier))+
  geom_col(position = position_dodge(), color = 'black')+
  facet_grid(
    qud ~ venn
  )+
  viridis::scale_fill_viridis(discrete = T)+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    strip.text.y = element_text(angle = 0)
  )
```


## Make single venn diagram

```{r}
make_single_venn <- function(venn_string){
  ggVennDiagram(
    get_venn_samples(unlist(str_split(venn_string, ";"))
  ), label = NULL, color = 'black') +
    # ggtitle(format_sentence(utt)) + 
    scale_fill_gradient(low = "white", high = "grey20",
                        limits = c(0, 1),
                        breaks = c(0, 1),
                        labels = c(0, 1),
                        name = "Probability")+
    guides(fill = F)+
    theme(plot.title = element_text(hjust = 0.5))
  
  ggsave(paste(
    "../publications/topics/figs/venn_",
    venn_string,
    ".pdf", sep = ""), width = 2.5, height = 2)
}
#make_single_venn(venn_string)
map(
  unique(wp.rs.s.marginals$venn),
  make_single_venn
)

```

# Full reasoner model (Distributions on conclusions)


```{r}
# marginalize_conclusion_dist = function(joint_dist, syllogism, modelName){
#   return (
#   data.frame(wp.rs[[syllogism]][[modelName]]) %>%
#   mutate(
#     syllogism = syllogism,
#      modelName = modelName
#   ))
# }

marginalize_conclusion_dist = function(joint_dist, syllogism){
  return (
  data.frame(wp.rs[[syllogism]]) %>%
  mutate(
    syllogism = syllogism#,
     # modelName = modelName
  ))
}
```

```{r}
wp.rs <- webppl(
  program_file = "venn-r-refac.wppl",
  data = "M00_LIT_LIT",
  data_var = "dataFromR",
  packages = c("./node_modules/vennUtils_oneShot")
  )

syllogisms = names(wp.rs)
# model_types = names(wp.rs[[syllogisms[1]]])


wp.rs.r.marginals <- bind_rows(
  map(syllogisms, function(syll){
    # map(model_types, function(modl){
      return(marginalize_conclusion_dist(wp.rs, syll))
    })
  # })
)

# wp.rs.r.marginals <- bind_rows(
#   map(syllogisms, function(syll){
#     map(model_types, function(modl){
#       return(marginalize_conclusion_dist(wp.rs, syll, modl))
#     })
#   })
# )

```



```{r}
wp.rs.r.marginals %>%
  rename(conclusion = support) %>%
  rowwise() %>%
  mutate(quantifier = str_split(conclusion, ";")[[1]][1],
         term_order = extract_term_order(conclusion),
         syllogism = format_sentence(syllogism),
         # modelName = factor(modelName, levels = c("literal", "pragmatic_state_lit",
         #                                          "pragmatic_AC_lit")),
         quantifier = factor(quantifier, levels = c("All", "Some",
                                                    "Some not", "No", "NVC")),
         conclusion = factor(conclusion,
                             levels = c("All;A;C","All;C;A",
                                        "Some;A;C", "Some;C;A",
                                        "Some not;A;C", "Some not;C;A",
                                        "No;A;C","No;C;A",
                                        "NVC;"))) -> wp.rs.r.marginals.formatted
  
ggplot(wp.rs.r.marginals.formatted, 
       aes( fill = quantifier, y = probs,
                               x = conclusion, group = term_order))+
  geom_col(position = position_dodge(), color = 'black')+
  # facet_grid(
  #   syllogism ~ modelName
  # )+
  facet_wrap(~syllogism)+
  viridis::scale_fill_viridis(discrete = T)+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    strip.text.y = element_text(angle = 0)
  )
```


Empirical means
```{r}
df.ragni.altModel.full.summary <-read_csv(file = "../publications/topics/cached_results/phm-mReasoner-ragni-summary.csv")

df.ragni.altModel.full.summary %>% 
  select(-model, -model_lower, -model_mean, -model_upper) %>%
  distinct(premise_1, premise_2, conclusion, mean, ci_lower, ci_upper, conclusion_quantifier) %>%
  rowwise() %>%
  mutate(
    syllogism = paste(premise_1, "/", premise_2, sep = ""),
    syllogism = format_sentence(syllogism),
    modelName = 'data'
  ) %>%
  select(-premise_1, -premise_2) %>%
  filter(syllogism %in% unique(wp.rs.r.marginals.formatted$syllogism)) %>%
  bind_rows(., 
            wp.rs.r.marginals.formatted %>%
              mutate(mean = probs, ci_lower = probs, ci_upper = probs) %>%
              rename(conclusion_quantifier = quantifier) %>%
              select(-probs, -term_order) 
              ) -> wp.rs.r.marginals.formatted.wData

ggplot(wp.rs.r.marginals.formatted.wData, 
       aes( fill = conclusion_quantifier, y = mean,
                               x = conclusion, group = conclusion))+
  geom_col(position = position_dodge(), color = 'black')+
  facet_grid(
    syllogism ~ modelName
  )+
  viridis::scale_fill_viridis(discrete = T)+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    strip.text.y = element_text(angle = 0)
  )
```


